{% set name = "node-graph" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/node_graph-{{ version }}.tar.gz
  sha256: 5c4c4ba5cc2c2d3ae6de5601db796034dd2fa0a7b7f26eaa69e53a9fb96aaa41

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - click
    - pyyaml
    - colorama
    - termcolor
    - cloudpickle

test:
  imports:
    - node_graph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Create node-based workflow
  home: https://github.com/scinode/node-graph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
