{% set name = "node-graph" %}
{% set version = "0.1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/node_graph-{{ version }}.tar.gz
  sha256: 09565396b433f0b3a06a5d354b3de29063774549d6c8d7498c005cb22a7546a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - node-graph-widget
    - python >={{ python_min }}
    - numpy
    - scipy
    - click
    - pyyaml
    - colorama
    - termcolor
    - cloudpickle

test:
  imports:
    - node_graph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Create node-based workflow
  home: https://github.com/scinode/node-graph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
