{% set name = "node-graph" %}
{% set version = "0.2.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/node_graph-{{ version }}.tar.gz
  sha256: 38a5a9cb2adae2cc781e1d88a99f6f6b4454128d7f871b4c3cd9e71bcb7b59eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - node-graph-widget
    - python >={{ python_min }}
    - numpy
    - scipy
    - click
    - pyyaml
    - colorama
    - termcolor
    - cloudpickle

test:
  imports:
    - node_graph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Create node-based workflow
  home: https://github.com/scinode/node-graph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
