{% set name = "node-graph" %}
{% set version = "0.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/node_graph-{{ version }}.tar.gz
  sha256: 4888ced414daaed88ff21fb5ec18bedc51ad3a01bf426768af507459e1c98868

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2
    - pip
  run:
    - pydantic >=2.6,<3.dev0
    - wrapt
    - node-graph-widget
    - python >={{ python_min }}
    - numpy
    - scipy
    - click
    - pyyaml
    - colorama
    - termcolor
    - cloudpickle

test:
  imports:
    - node_graph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Create node-based workflow
  home: https://github.com/scinode/node-graph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
